@@include('files/regular.js', {})
@@include('files/script.js', {})
@@include('files/functions.js', {})
@@include('files/forms.js', {})
@@include('files/scroll.js', {})
@@include('files/responsive.js', {})
@@include('files/map.js', {})